name: My pipeline
on: workflow_dispatch
permissions:
  id-token: write
  contents: read  

jobs:
  terraform-init-plan:
    name: My first job
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 5bba0a5a-f12e-430f-a7d7-4aa9ae6db51e
          tenant-id: e0eb0b0e-a455-477c-b0e8-56b7f7f4efb4
          subscription-id: 177b7e12-5f03-4f63-bcd1-ed6d1d776bff
         
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: /dev  

      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: /dev 

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: /dev        
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: /dev 
        
          

          
                
        
