name: CI

# on:
#   pull_request:
#     # Sequence of patterns matched against refs/heads
#     branches:
#       - main
#       - 'mona/octocat'
#       - 'releases/**'

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

jobs:
  build:
    name: Terraform Plan
    runs-on: self-hosted
    steps:
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL }}
          # When use client credential
          # client-id: ${{ secrets.CLIENT_ID }}
          # client-secret: ${{ secrets.CLIENT_SECRET }}
          # tenant-id: ${{ secrets.TENANT_ID }}
          # subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          
          # When use client Workload Federation credential
          # client-id: ${{ secrets.CLIENT_ID }}
          # tenant-id: ${{ secrets.TENANT_ID }}
          # subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      - name: Terraform Init
        id: init
        run: |
          terraform init -input=false \
            -backend-config="resource_group_name=${{ secrets.RG_NAME }}" \
            -backend-config="storage_account_name=${{ secrets.STG_NAME }}" \
            -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
            -backend-config="key=${{ secrets.STATE_KEY }}"
        working-directory: dev
      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false  
        working-directory: dev

          
          
                
          
          
          
  

    
  
